version: '3'

services:
  mysql-standalone:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sample
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    volumes:
      - /data/mysql
  run11:
    image: final6
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone
    ports:
      - 8085:8085
    volumes:
      - /data/final6